# Generated by Django 5.2.4 on 2025-08-05 10:54

import apps.products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(max_length=400, upload_to=apps.products.models.product_image_path),
        ),
    ]
