# Generated by Django 5.2.4 on 2025-08-05 11:29

import apps.products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_productimage_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, max_length=400, null=True, upload_to=apps.products.models.product_image_path),
        ),
    ]
