# Generated by Django 5.2.4 on 2025-08-05 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-discount']},
        ),
    ]
