# Generated by Django 5.2.4 on 2025-08-07 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_remove_productvariant_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
