# Generated by Django 5.2.4 on 2025-08-07 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_productvariant_quantity_alter_productvariant_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariant',
            old_name='quantity',
            new_name='stock',
        ),
    ]
