# Generated by Django 5.2.4 on 2025-08-07 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_rename_quantity_productvariant_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quantity',
            new_name='stock',
        ),
    ]
