# Generated by Django 5.2.4 on 2025-08-22 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_variantimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='unique_name',
            field=models.CharField(default='name'),
        ),
    ]
