# Generated by Django 5.2.4 on 2025-08-23 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_productvariant_unique_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variantimage',
            old_name='variant',
            new_name='product',
        ),
    ]
