# Generated by Django 5.2.4 on 2025-08-23 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_rename_variant_variantimage_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variantimage',
            old_name='product',
            new_name='variant',
        ),
    ]
