# Generated by Django 5.2.4 on 2025-08-24 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_rename_product_variantimage_variant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariant',
            old_name='unique_name',
            new_name='identifiant',
        ),
    ]
