# Generated by Django 5.2.4 on 2025-08-27 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_rename_unique_name_productvariant_identifiant'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='old_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
