# Generated by Django 5.2.4 on 2025-12-18 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='identifiant',
            field=models.CharField(default='name', max_length=255),
        ),
        migrations.AlterField(
            model_name='variantimage',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_image', to='products.productvariant'),
        ),
    ]
