# Generated by Django 5.2.4 on 2026-05-16 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_alter_productvariant_identifiant_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
    ]
