# Generated by Django 5.2.4 on 2026-05-16 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
