# Generated by Django 5.2.4 on 2025-11-07 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_rename_user_order_customer_id_order_order_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='valid_to',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='valid_from',
            field=models.DateField(auto_now=True),
        ),
    ]
