# Generated by Django 5.2.4 on 2025-11-07 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_payment_shipping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='valid_from',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='valid_to',
            field=models.DateField(),
        ),
    ]
