# Generated by Django 5.2.4 on 2025-11-17 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_alter_promocode_valid_from_alter_promocode_valid_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='promo_code',
        ),
        migrations.DeleteModel(
            name='PromoCode',
        ),
    ]
