# Generated by Django 5.2.4 on 2025-11-19 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_order_shipping_address_order_shipping_cost_order_vat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('shipped', 'Shipped'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('refunded_insufficient_stock', 'RefundedInsufficientStock')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('paypal', 'Paypal'), ('stripe', 'Stripe'), ('credit_card', 'Credit Card'), ('cash_on_delivery', 'Cash on Delivery')]),
        ),
    ]
