# Generated by Django 5.2.4 on 2025-11-20 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0008_alter_order_discount_amount_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='USD', max_length=10),
        ),
    ]
