# Generated by Django 5.2.4 on 2025-11-20 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0009_payment_currency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='transaction_id',
            new_name='stripe_payment_intent_id',
        ),
    ]
