# Generated by Django 5.2.4 on 2025-11-20 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0010_rename_transaction_id_payment_stripe_payment_intent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='paied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='stripe_session_id',
            field=models.TextField(default='1234'),
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(default='SDQSA', max_length=255),
        ),
        migrations.AlterField(
            model_name='payment',
            name='stripe_payment_intent_id',
            field=models.TextField(default='67N9717781765035V'),
        ),
    ]
