# Generated by Django 5.2.4 on 2025-11-20 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0011_payment_paied_at_payment_stripe_session_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='stripe_payment_intent_id',
            field=models.TextField(default='67N9717781765035V', null=True),
        ),
    ]
