# Generated by Django 5.2.4 on 2025-11-22 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0013_order_cart_alter_order_order_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_price',
            new_name='subtotal',
        ),
    ]
