# Generated by Django 5.2.4 on 2025-11-22 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0014_rename_total_price_order_subtotal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
    ]
