# Generated by Django 5.2.4 on 2025-11-22 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0016_orderitem_variant_alter_orderitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='image_url',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
