# Generated by Django 5.2.4 on 2025-11-22 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0017_orderitem_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('paypal', 'Paypal'), ('stripe', 'Stripe'), ('card', 'Credit Card'), ('cash_on_delivery', 'Cash on Delivery')]),
        ),
    ]
