# Generated by Django 5.2.4 on 2025-11-22 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0018_alter_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('paypal', 'Paypal'), ('stripe', 'Stripe')], default='stripe'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('card', 'Credit Card'), ('cash_on_delivery', 'Cash on Delivery')]),
        ),
    ]
