# Generated by Django 5.2.4 on 2025-11-27 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0019_payment_provider_alter_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='failure_reason',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
