# Generated by Django 5.2.4 on 2025-08-01 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_pendingemailchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='social_media_username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
