# Generated by Django 5.2.4 on 2025-08-01 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_social_media_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='reset_token_used',
            field=models.BooleanField(default=False),
        ),
    ]
