# Generated by Django 5.2.4 on 2025-08-05 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userprofile_reset_token_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='password_reset_completed',
            field=models.BooleanField(default=False),
        ),
    ]
