# Generated by Django 5.2.4 on 2025-09-03 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userprofile_password_reset_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='password_reset_completed',
        ),
    ]
